TaskPlanner/TaskPlannerWeb/Models/EmployeeViewModel.cs
using BusinessLogicLevel.Models;
using System.ComponentModel;

namespace TaskPlannerWeb.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [DisplayName("Free hours")]
        public int FreeHours { get; set; }
        public List<TaskModel> Tasks { get; set; } = new List<TaskModel>();
    }
}

TaskPlanner/TaskPlannerWeb/Models/ErrorViewModel.cs
namespace TaskPlannerWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskPlanner/TaskPlannerWeb/Models/TaskViewModel.cs
using SharedTypes.Enums;
using System.ComponentModel;

namespace TaskPlannerWeb.Models
{
    public class TaskViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string? Description { get; set; }
        [DisplayName("Estimated Time")]
        public int EstimatedTime { get; set; }
        [DisplayName("Task Priority")]
        public TaskPriority TaskPriority { get; set; }
        [DisplayName("Task Status")]
        public SharedTypes.Enums.TaskStatus TaskStatus { get; set; }
    }
}

TaskPlanner/TaskPlannerWeb/Controllers/EmployeeController.cs
using AutoMapper;
using BusinessLogicLevel.Interfaces;
using BusinessLogicLevel.Models;
using BusinessLogicLevel.Services;
using Microsoft.AspNetCore.Mvc;
using TaskPlannerWeb.Models;

namespace TaskPlannerWeb.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IMapper _mapper;
        public EmployeeController(IEmployeeService employeeService, IMapper mapper)
        {
            _employeeService = employeeService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var employees = _employeeService.GetEmployees();
            return View(_mapper.Map<IEnumerable<EmployeeViewModel>>(employees));
        }
        public IActionResult Create()//get
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EmployeeViewModel obj)//post
        {
            _employeeService.AddEmployee(_mapper.Map<EmployeeModel>(obj));
            TempData["success"] = "Employee created successfully";
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int? id)//todo: move all logic to bll
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var employee = _employeeService.GetEmployeeById(id.Value);
            return View(_mapper.Map<EmployeeViewModel>(employee));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EmployeeViewModel obj)//post
        {
            _employeeService.EditEmployee(_mapper.Map<EmployeeModel>(obj));
            TempData["success"] = "Employee edited successfully";
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int? id)
        {
            if (IsValidIdentifier(id))
            {
                return NotFound();
            }
            _employeeService.RemoveEmployee((int)id);
            TempData["success"] = "Employee removed successfully";
            return RedirectToAction("Index");
        }
        private bool IsValidIdentifier(int? id)
        {
            return !(id.HasValue || id == 0);
        }

    }
}

TaskPlanner/TaskPlannerWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TaskPlannerWeb.Models;

namespace TaskPlannerWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TaskPlanner/TaskPlannerWeb/Controllers/TaskController.cs
using AutoMapper;
using BusinessLogicLevel.Interfaces;
using BusinessLogicLevel.Models;
using Microsoft.AspNetCore.Mvc;
using TaskPlannerWeb.Models;

namespace TaskPlannerWeb.Controllers
{
    public class TaskController : Controller
    {
        private readonly ITaskService _taskService;
        private readonly IMapper _mapper;
        public TaskController(ITaskService taskService, IMapper mapper)
        {
            _taskService = taskService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            IEnumerable<TaskViewModel> tasks = _mapper.Map<IEnumerable<TaskViewModel>>(_taskService.GetTasks());
            return View(tasks);
        }
        public IActionResult Create()//get
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TaskViewModel obj)//post
        {
            _taskService.CreateTask(_mapper.Map<TaskModel>(obj));
            TempData["success"] = "Task created successfully";
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int? id)//todo: move all logic to bll
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var task = _taskService.GetTaskById((int)id);
            return View(_mapper.Map<TaskViewModel>(task));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TaskViewModel obj)//post
        {
            _taskService.EditTask(_mapper.Map<TaskModel>(obj));
            TempData["success"] = "Task edited successfully";
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int? id)//todo: move all logic to bll
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            _taskService.DeleteTask((int)id);
            TempData["success"] = "Task deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

TaskPlanner/TaskPlannerWeb/Views/Employee/Create.cshtml
@model EmployeeViewModel

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">   
            <h2 class="text-primary">Add new Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FreeHours"></label>
            <input asp-for="FreeHours" class="form-control" />
        </div>
@*        <div class="form-group mb-3">
            <label asp-for="TaskPriority" class="control-label"></label>
            <select asp-for="TaskPriority" class="form-control" 
            asp-items="Html.GetEnumSelectList<TaskPriority>()"></select>
        </div>*@
        <button type="submit" class="btn btn-primary" style="width:150px">Add</button>
        <a asp-controller="Employee" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

TaskPlanner/TaskPlannerWeb/Views/Employee/Edit.cshtml
@model EmployeeViewModel

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Employee</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FreeHours"></label>
            <input asp-for="FreeHours" class="form-control" />
        </div>
        @*        <div class="form-group mb-3">
        <label asp-for="TaskPriority" class="control-label"></label>
        <select asp-for="TaskPriority" class="form-control"
        asp-items="Html.GetEnumSelectList<TaskPriority>()"></select>
        </div>*@
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Employee" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

TaskPlanner/TaskPlannerWeb/Views/Employee/Index.cshtml
@model IEnumerable<EmployeeViewModel>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Employees</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Employee" asp-action="Create" class="btn btn-primary">
                Add new Employee
            </a>
        </div>
    </div>
    <br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Free hours
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="20%">
                        @item.Name
                    </td>
                    <td width="20%">
                        @item.FreeHours
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Employee" asp-action="Edit" asp-route-id="@item.Id"
                           class="btn btn-primary mx-2">Edit</a>
                        </div>
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Employee" asp-action="Delete" asp-route-id="@item.Id"
                           class="btn btn-danger mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

TaskPlanner/TaskPlannerWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h2 class="display-4">Welcome to TaskPlanner</h2>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TaskPlanner/TaskPlannerWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskPlannerWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/pulseTheme.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/TaskPlannerWeb.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskPlannerWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaskPlannerWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>*@
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskPlanner/TaskPlannerWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

TaskPlanner/TaskPlannerWeb/Views/Task/Create.cshtml
@using SharedTypes.Enums;
@model TaskViewModel

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">   
            <h2 class="text-primary">Add new Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="EstimatedTime"></label>
            <input asp-for="EstimatedTime" class="form-control" />
            <span asp-validation-for="EstimatedTime" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="TaskPriority" class="control-label"></label>
            <select asp-for="TaskPriority" class="form-control" 
            asp-items="Html.GetEnumSelectList<TaskPriority>()"></select>
        </div>
        <div class="form-group mb-3">
            <label asp-for="TaskStatus" class="control-label"></label>
            <select asp-for="TaskStatus" class="form-control"
                    asp-items="Html.GetEnumSelectList<SharedTypes.Enums.TaskStatus>()"></select>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Add</button>
        <a asp-controller="Task" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

TaskPlanner/TaskPlannerWeb/Views/Task/Edit.cshtml
@using SharedTypes.Enums;
@model TaskViewModel

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">   
            <h2 class="text-primary">Edit Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="EstimatedTime"></label>
            <input asp-for="EstimatedTime" class="form-control" />
            <span asp-validation-for="EstimatedTime" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="TaskPriority" class="control-label"></label>
            <select asp-for="TaskPriority" class="form-control"
                    asp-items="Html.GetEnumSelectList<TaskPriority>()"></select>
        </div>
        <div class="form-group mb-3">
            <label asp-for="TaskStatus" class="control-label"></label>
            <select asp-for="TaskStatus" class="form-control"
                    asp-items="Html.GetEnumSelectList<SharedTypes.Enums.TaskStatus>()"></select>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Task" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

TaskPlanner/TaskPlannerWeb/Views/Task/Index.cshtml
@model IEnumerable<TaskViewModel>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Tasks</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Task" asp-action="Create" class="btn btn-primary">
                Add new Task
            </a>
        </div>
    </div>
    <br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Description
            </th>
            <th>
                Estimated time (hours)
            </th>
            <th>
                Priority
            </th>
            <th>
                Status
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="20%">
                    @item.Title
                </td>
                <td width="40%">
                    @item.Description
                </td>
                <td width="20%">
                    @item.EstimatedTime
                </td>
                <td width="10%">
                    @item.TaskPriority
                </td>
                <td width="10%">
                    @item.TaskStatus
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Task" asp-action="Edit" asp-route-id="@item.Id"
                        class="btn btn-primary mx-2">Edit</a>
                    </div>
                </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Task" asp-action="Delete" asp-route-id="@item.Id"
                           class="btn btn-danger mx-2">Delete</a>
                        </div>
                    </td>
            </tr>
        }
    </tbody>
</table>

</div>